#  Meta Ad Performance Dashboard | Power BI Project

![Dashboard Preview](https://github.com/Khushi-Tipare/meta-data-analytics-powerbi/blob/main/Facebook%20Dashboard.png)
---

#   Project Overview

The **Meta Ad Performance Dashboard** is a comprehensive **Power BI Business Intelligence project** developed to analyze and monitor advertising campaign performance across **Facebook** and **Instagram** platforms.

This dashboard enables marketing teams and business stakeholders to:
- Track campaign performance in real time
- Measure engagement and conversion efficiency
- Analyze audience demographics
- Monitor budget utilization
- Identify high-performing ad formats and regions
- Make data-driven marketing decisions

The report combines **interactive visualizations**, **dynamic KPIs**, and **business insights** to provide a complete overview of Meta advertising performance.

---

#   Business Problem

Marketing teams running campaigns on Meta platforms often struggle to:
- Measure ROI effectively
- Identify the best-performing audience segments
- Understand engagement patterns
- Optimize ad spend
- Compare campaign performance across platforms

This dashboard solves these challenges by centralizing all campaign analytics into one interactive reporting solution.

---

# Tools & Technologies Used

| Technology | Purpose |
|------------|---------|
| **Power BI Desktop** | Dashboard Development |
| **Power Query** | Data Cleaning & Transformation |
| **DAX** | KPI Measures & Calculations |
| **Data Modeling** | Relationship Management |
| **Excel / CSV Files** | Data Source |
| **GitHub** | Project Version Control |

---

#  Dataset Information

The project uses advertising campaign datasets containing Meta ad performance information.

## Dataset Includes:
- Campaign Details
- User Demographics
- Ad Events
- Engagement Metrics
- Budget Information
- Geographic Data
- Platform Details

---

#  Data Model

The dashboard was built using multiple related tables including:

| Table Name | Description |
|------------|-------------|
| `campaigns` | Campaign-level information and budget |
| `ads` | Ad details including ad type and audience |
| `ad_events` | User interaction events |
| `users` | User demographic and location data |
| `date_table` | Calendar and time analysis |

---

# 📸 Dataset Preview

## Ads Dataset
![Ads Dataset](https://github.com/Khushi-Tipare/meta-data-analytics-powerbi/blob/main/ads.csv)

## Campaign Dataset
![Campaign Dataset](https://github.com/Khushi-Tipare/meta-data-analytics-powerbi/blob/main/campaigns.csv)

## Ad Events Dataset
![Ad Events Dataset](https://github.com/Khushi-Tipare/meta-data-analytics-powerbi/blob/main/ad_events.csv)

## Users Dataset
![Users Dataset](https://github.com/Khushi-Tipare/meta-data-analytics-powerbi/blob/main/users.csv)



---

#  Key Performance Indicators (KPIs)

| KPI | Value | Description |
|------|------|-------------|
| Impressions | 216K | Total ad views |
| Clicks | 25.4K | Total ad clicks |
| Shares | 1.3K | Total shares |
| Comments | 2.6K | Total comments |
| Purchases | 1.3K | Total conversions |
| Engagements | 29.3K | Total interactions |
| CTR | 11.76% | Click-through rate |
| Engagement Rate | 13.56% | Interaction efficiency |
| Conversion Rate | 5.21% | Click-to-purchase ratio |
| Purchase Rate | 0.61% | Purchase per impression |
| Total Budget | 2.54M | Total campaign spend |
| Avg Budget per Campaign | 50.72K | Average campaign allocation |

---

#  Dashboard Features

##  KPI Cards
Displays high-level business metrics:
- Impressions
- Clicks
- Shares
- Comments
- Purchases
- Budget Metrics
- Conversion Metrics

---

##  Gender Analysis (Donut Chart)
Analyzes engagement contribution by:
- Male
- Female
- Other

### Insight:
Female audiences contribute the highest engagement.

---

##  Age Group Analysis (Bar Chart)
Tracks performance across audience age groups.

### Insight:
The **18–30 age group** shows the highest engagement and interaction levels.

---

##  Geographic Analysis (Country-Level)
Compares campaign performance across countries.

### Top Performing Countries:
- United States
- India
- Brazil
- Germany
- United Kingdom

### Insight:
India and the US show strong engagement potential.

---

## Weekly Trend Analysis
Stacked column chart showing weekly performance trends by ad type.

### Insight:
Campaign performance remains consistent across weeks with no major drops.

---

## Hourly Trend Analysis
Area chart showing engagement patterns by hour.

### Insight:
Peak engagement occurs during afternoon and evening hours.

---

##  Calendar Heatmap
Visualizes campaign activity by date.

### Insight:
Higher engagement observed during:
- 19th–21st
- 25th–27th

Likely due to promotions or campaign launches.

---

##  Ad Type Performance Matrix

| Ad Type | Performance Summary |
|----------|--------------------|
| Video Ads | Highest CTR & Engagement |
| Story Ads | Highest Impressions |
| Carousel Ads | Good engagement performance |
| Image Ads | Moderate conversions |

### Insight:
Video ads perform best overall.

---

# Dashboard Screenshots

## Facebook Dashboard
[Facebook Dashboard]https://github.com/Khushi-Tipare/meta-data-analytics-powerbi/blob/main/Facebook%20Dashboard.png

---

## Instagram Dashboard
[Instagram Dashboard]https://github.com/Khushi-Tipare/meta-data-analytics-powerbi/blob/main/Instagram%20Dashboard.png

---

#  Detailed Business Insights

##   Awareness & Engagement
- High CTR (11.76%) indicates strong ad attractiveness.
- High Engagement Rate (13.56%) shows audience interest.

---

##   Conversion Funnel Analysis
- Purchase Rate remains low at 0.61%.
- Strong upper funnel performance but weaker purchase conversion.

### Recommendation:
Improve:
- Landing pages
- Retargeting strategy
- Checkout experience

---

##   Audience Targeting Insights
Best-performing audience:
- Females
- Age Group: 18–30

### Recommendation:
Increase targeting toward young female audiences.

---

##   Geographic Strategy
High-performing countries:
- India
- United States
- Brazil

### Recommendation:
Allocate higher budgets to these regions.

---

##   Ad Format Insights
Best-performing ad formats:
1. Video Ads
2. Story Ads

### Recommendation:
Shift more campaign budget toward video-based content.

---

##    Timing Insights
Highest engagement observed during:
- Afternoon
- Evening Hours

### Recommendation:
Schedule campaigns during peak activity hours.

---

#   Final Recommendations

✔ Increase investment in Video & Story Ads  
✔ Improve landing page conversion strategy  
✔ Focus on Females aged 18–30  
✔ Optimize campaigns for India & US  
✔ Schedule ads during high-engagement hours  
✔ Use retargeting campaigns to improve purchases  

---

#   Project Structure

```bash
Meta-Ad-Performance-Dashboard
 ┣  Meta Dashboard.pbix
 ┣  README.md
 ┣  Facebook Dashboard.png
 ┣  ads_dataset.png
 ┣  campaign_dataset.png
 ┣  ad_events_dataset.png
 ┣  users_dataset.png
 ┣  Business Requirements Document.pdf
 ┗ Dashboard Insights.pdf
```

---



#   Skills Demonstrated

- Power BI Dashboard Design
- DAX Measures
- Data Modeling
- Power Query Transformation
- Business Intelligence
- Marketing Analytics
- Data Storytelling
- Insight Generation

---

#   Author

## Khushi Tipare

### Connect With Me
- LinkedIn: https://www.linkedin.com/in/khushitipare24


---
